service: aws-task-manager
frameworkVersion: "3"

custom:
  tableName: TasksTable
  url: http://localhost:5500

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
  httpApi:
    cors:
      allowedOrigins:
        - ${self:custom.url}
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowCredentials: true
  environment:
    tableName: ${self:custom.tableName}
functions:
  getTasks:
    handler: index.handler
    events:
      - httpApi:
          path: /tasks
          method: GET
  getOneTask:
    handler: index.handler
    events:
      - httpApi:
          path: /tasks/{taskId}
          method: GET
  CreateTask:
    handler: index.handler
    events:
      - httpApi:
          path: /tasks
          method: POST
  editTask:
    handler: index.handler
    events:
      - httpApi:
          path: /tasks/{taskId}
          method: PUT
  deleteTask:
    handler: index.handler
    events:
      - httpApi:
          path: /tasks/{taskId}
          method: DELETE

resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: taskId
            AttributeType: S
        KeySchema:
          - AttributeName: taskId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
